In [1]:
import numpy as np
import pandas as pd
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

In [2]:
#Sample text data

text_data = ["hello how are you",
            "hello how have you been",
            "hi there",
            "good morning",
            "good night",
            "have a nice day",
            "how is it going",
            "how have you been",
            "nice to meet you"
            "thank you"]


In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)
total_words = len(tokenizer.word_index)+1

In [4]:
total_words

21

In [5]:
tokenizer.word_index

{'how': 1,
 'you': 2,
 'have': 3,
 'hello': 4,
 'been': 5,
 'good': 6,
 'nice': 7,
 'are': 8,
 'hi': 9,
 'there': 10,
 'morning': 11,
 'night': 12,
 'a': 13,
 'day': 14,
 'is': 15,
 'it': 16,
 'going': 17,
 'to': 18,
 'meet': 19,
 'youthank': 20}

In [6]:
#Prepare the input sequence

input_sequences = []
for line in text_data:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [7]:
input_sequences

[[4, 1],
 [4, 1, 8],
 [4, 1, 8, 2],
 [4, 1],
 [4, 1, 3],
 [4, 1, 3, 2],
 [4, 1, 3, 2, 5],
 [9, 10],
 [6, 11],
 [6, 12],
 [3, 13],
 [3, 13, 7],
 [3, 13, 7, 14],
 [1, 15],
 [1, 15, 16],
 [1, 15, 16, 17],
 [1, 3],
 [1, 3, 2],
 [1, 3, 2, 5],
 [7, 18],
 [7, 18, 19],
 [7, 18, 19, 20],
 [7, 18, 19, 20, 2]]

In [8]:
#### Pad Sequences
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')

In [9]:
input_sequences

array([[ 0,  0,  0,  4,  1],
       [ 0,  0,  4,  1,  8],
       [ 0,  4,  1,  8,  2],
       [ 0,  0,  0,  4,  1],
       [ 0,  0,  4,  1,  3],
       [ 0,  4,  1,  3,  2],
       [ 4,  1,  3,  2,  5],
       [ 0,  0,  0,  9, 10],
       [ 0,  0,  0,  6, 11],
       [ 0,  0,  0,  6, 12],
       [ 0,  0,  0,  3, 13],
       [ 0,  0,  3, 13,  7],
       [ 0,  3, 13,  7, 14],
       [ 0,  0,  0,  1, 15],
       [ 0,  0,  1, 15, 16],
       [ 0,  1, 15, 16, 17],
       [ 0,  0,  0,  1,  3],
       [ 0,  0,  1,  3,  2],
       [ 0,  1,  3,  2,  5],
       [ 0,  0,  0,  7, 18],
       [ 0,  0,  7, 18, 19],
       [ 0,  7, 18, 19, 20],
       [ 7, 18, 19, 20,  2]])

In [10]:
input_sequences.shape

(23, 5)

In [11]:
## Split into features and labels
import keras
input_sequences = np.array(input_sequences)
X, y = input_sequences[:,:-1], input_sequences[:,-1]
y = keras.utils.to_categorical(y, num_classes = total_words)

In [12]:
input_sequences[:,-1]

array([ 1,  8,  2,  1,  3,  2,  5, 10, 11, 12, 13,  7, 14, 15, 16, 17,  3,
        2,  5, 18, 19, 20,  2])

In [13]:
y

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.,

In [14]:
## Build the RNN model
model = Sequential()
model.add(Embedding(total_words, 10, input_length=max_sequence_len-1))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(total_words, activation="softmax"))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 10)             210       
                                                                 
 lstm (LSTM)                 (None, 4, 150)            96600     
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 21)                2121      
                                                                 
Total params: 199331 (778.64 KB)
Trainable params: 199331 (778.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Compile the model

In [16]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [17]:
model.fit(X, y, epochs = 200, batch_size=1)

Epoch 1/200


23/23 [==============================] - 4s 9ms/step - loss: 3.0484 - accuracy: 0.0000e+00
Epoch 2/200
23/23 [==============================] - 0s 9ms/step - loss: 3.0200 - accuracy: 0.1739
Epoch 3/200
23/23 [==============================] - 0s 9ms/step - loss: 2.9738 - accuracy: 0.1739
Epoch 4/200
23/23 [==============================] - 0s 9ms/step - loss: 2.8488 - accuracy: 0.1739
Epoch 5/200
23/23 [==============================] - 0s 9ms/step - loss: 2.7912 - accuracy: 0.1739
Epoch 6/200
23/23 [==============================] - 0s 9ms/step - loss: 2.7403 - accuracy: 0.1739
Epoch 7/200
23/23 [==============================] - 0s 9ms/step - loss: 2.6662 - accuracy: 0.1739
Epoch 8/200
23/23 [==============================] - 0s 9ms/step - loss: 2.5762 - accuracy: 0.1739
Epoch 9/200
23/23 [==============================] - 0s 8ms/step - loss: 2.5042 - accuracy: 0.1739
Epoch 10/200
23/23 [==============================] - 0s 8ms/step - loss: 2.4167 - accuracy: 0.1739
Epo

23/23 [==============================] - 0s 8ms/step - loss: 0.2273 - accuracy: 0.7826
Epoch 78/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2231 - accuracy: 0.7391
Epoch 79/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2185 - accuracy: 0.8261
Epoch 80/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2225 - accuracy: 0.7826
Epoch 81/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2181 - accuracy: 0.7826
Epoch 82/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2182 - accuracy: 0.7826
Epoch 83/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2120 - accuracy: 0.7826
Epoch 84/200
23/23 [==============================] - 0s 8ms/step - loss: 0.2147 - accuracy: 0.7826
Epoch 85/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2147 - accuracy: 0.8696
Epoch 86/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2108 - accuracy: 0.8261
Epoch 87/20

23/23 [==============================] - 0s 9ms/step - loss: 0.1954 - accuracy: 0.8261
Epoch 159/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2095 - accuracy: 0.7826
Epoch 160/200
23/23 [==============================] - 0s 9ms/step - loss: 0.1938 - accuracy: 0.8261
Epoch 161/200
23/23 [==============================] - 0s 9ms/step - loss: 0.1922 - accuracy: 0.8261
Epoch 162/200
23/23 [==============================] - 0s 10ms/step - loss: 0.1954 - accuracy: 0.8261
Epoch 163/200
23/23 [==============================] - 0s 10ms/step - loss: 0.1970 - accuracy: 0.8261
Epoch 164/200
23/23 [==============================] - 0s 10ms/step - loss: 0.1990 - accuracy: 0.8696
Epoch 165/200
23/23 [==============================] - 0s 10ms/step - loss: 0.1969 - accuracy: 0.7826
Epoch 166/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2134 - accuracy: 0.8261
Epoch 167/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2008 - accuracy: 0.826

### Prediction on new data

In [18]:
# def predict_next_word(model, tokenizer, new, max_sequence_len):
#     token_list = tokenizer.texts_to_sequences(new)
#     return token_list

In [21]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen = max_sequence_len-1, padding='pre')
    predicted =  model.predict(token_list, verbose=0)
    predict_word_index = np.argmax(predicted)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predict_word_index:
            output_word=word
            break
    return output_word

In [22]:
new ='nice'
next_word = predict_next_word(model, tokenizer, new, max_sequence_len)
print(f"Next Word: {next_word}")


Next Word: to
