In [ ]:
pip install transformers

In [ ]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification


In [ ]:
model_name="bert-base-uncased"
tokenizer=BertTokenizer.from_pretrained(model_name)
model=TFBertForSequenceClassification.from_pretrained(model_name,num_labels=2)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
#Definw the rtext we want to classify
texts =["This is the best product.","This is the bad goods I have  received."]

In [ ]:
#Tokenize the text
inputs=tokenizer(texts,padding=True,truncation=True,return_tensors="tf",max_length=30)

#Get the model's predictions
outputs=model(inputs)
predictions=tf.argmax(outputs.logits,axis=-1)

In [ ]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.6670228 , -0.3145874 ],
       [ 0.6374519 , -0.27873608]], dtype=float32)>, hidden_states=None, attentions=None)

In [ ]:
predictions

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>